# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 03:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedata',
            name='page_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='page_url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
